[default]
locale = "en-au"

extend-ignore-re = [
    "(?Rm)^.*(#|//|%)\\s*spellchecker:disable-line$",                    # Line ignore with trailing `# spellchecker:disable-line`
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on", # Line block with `# spellchecker:<on|off>`
    "[A-Z]+s",                                                           # WORDs
]

[type.tex]
extend-ignore-re = [
    "\\{[^}]+}", # {word}
    "\\w+\\\\\\^\\{\\\\[^}]+}\\w+", # word\^{\...}word
]

[type.tex.extend-words]
center = "center"
wht = "wht"
SNooPY = "SNooPY"

